#!/usr/bin/env python3
# --------------------( LICENSE                            )--------------------
# Copyright (c) 2024-2026 Beartype authors.
# See "LICENSE" for further details.

'''
Beartype-specific **fixture type-checkers** (i.e., high-level factory functions
creating and returning closures wrapping the passed :mod:`pytest` fixtures with
:mod:`beartype`-backed type-checking).
'''

# ....................{ IMPORTS                            }....................
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# CAUTION: Importing from the external "beartype" package is acceptable *ONLY*
# from within this subpackage.
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
from beartype import beartype
from beartype.roar import BeartypeException
from collections.abc import Callable
from functools import wraps

# ....................{ CLASSES                            }....................
@beartype
class BeartypeFixtureFailure(object):
    '''
    **Fixture failure** (i.e., placeholder object wrapping a :mod:`pytest`
    fixture that violated one or more :mod:`beartype`-backed type-checks with
    details describing that violation).
    '''

    # ....................{ DUNDERS                        }....................
    def __init__(self, fixture_name: str, fixture_exception: Exception) -> None:
        '''
        Initialize this fixture failure.

        Parameters
        ----------
        fixture_name : str
            Fully-qualified name of the fixture that failed.
        fixture_exception : Exception
            Exception raised by beartype-based type-checking of this fixture.
        '''

        # Classify all passed parameters.
        self.fixture_name = fixture_name
        self.fixture_exception = fixture_exception

# ....................{ DECORATORS ~ sync                  }....................
@beartype
def beartype_fixture_sync_nongenerator(
    fixture_func: Callable, fixture_name: str) -> Callable:
    '''
    Custom :mod:`beartype` decorator unique to :mod:`pytest` synchronous
    non-generator fixtures, dynamically generating and returning a new
    :func:`beartype.beartype`-decorated synchronous non-generator fixture
    function wrapping the passed synchronous non-generator fixture function with
    type-checking.

    Parameters
    ----------
    fixture_func : Callable
        Low-level pure-Python function implementing this high-level fixture.
    fixture_name : str
        Fully-qualified name of this fixture.
    '''
    assert callable(fixture_func), f'{repr(fixture_func)} uncallable.'
    assert isinstance(fixture_name, str), f'{repr(fixture_name)} not string.'

    # Attempt to..
    try:
        # Function wrapping this fixture function with type-checking dynamically
        # generated by @beartype.
        fixture_func_checked = beartype(fixture_func)

        @wraps(fixture_func)
        def _beartype_fixture_wrapper(*args, **kwargs):
            f'''
            :func:`beartype.beartype`-decorated fixture function wrapping the
            original "{fixture_func.__qualname__}" fixture with type-checking.
            '''

            # Attempt to defer to this type-checked fixture function wrapper.
            try:
                return fixture_func_checked(*args, **kwargs)
            # If doing so raises a @beartype-specific call-time exception (e.g.,
            # due to type-checking violation), squelch this exception and return
            # a placeholder object encapsulating this exception instead.
            except BeartypeException as exception:
                return BeartypeFixtureFailure(fixture_name, exception)
    # If doing so raises *ANY* decoration-time exception (e.g., due to a
    # PEP-noncompliant type hint), squelch this exception and replace the
    # original fixture with a wrapper unconditionally returning a placeholder
    # object encapsulating this exception whenever called.
    except Exception as exception:
        @wraps(fixture_func)
        def _beartype_fixture_wrapper(
            *args, __beartype_exception__=exception, **kwargs):
            f'''
            Wrapper unconditionally returning a placeholder object encapsulating
            a decoration-time exception raised by the :func:`beartype.beartype`
            decorator on decorating the original "{fixture_func.__qualname__}"
            fixture with type-checking.

            Note that this exception is intentionally passed as a hidden
            optional ``__beartype_exception__`` parameter to this fixture
            wrapper. Why? Because if we do *not* do that, then CPython complains
            that the ``__beartype_exception__`` attribute is inaccessible to the
            body of this closure. Why? No idea. Closure mechanics frighten me,
            honestly:

                NameError: cannot access free variable '__beartype_exception__'
                where it is not associated with a value in enclosing scope
            '''

            # Return a placeholder object encapsulating this exception.
            return BeartypeFixtureFailure(fixture_name, __beartype_exception__)

    # Return this @beartype-decorated fixture wrapper.
    return _beartype_fixture_wrapper


@beartype
def beartype_fixture_sync_generator(
    fixture_func: Callable, fixture_name: str) -> Callable:
    '''
    Custom :mod:`beartype` decorator unique to :mod:`pytest` synchronous
    generator fixtures, dynamically generating and returning a new
    :func:`beartype.beartype`-decorated synchronous generator fixture function
    wrapping the passed synchronous generator fixture function with
    type-checking.

    Parameters
    ----------
    fixture_func : Generator
        Low-level pure-Python generator implementing this high-level fixture.
    fixture_name : str
        Fully-qualified name of this fixture.
    '''
    assert callable(fixture_func), f'{repr(fixture_func)} uncallable.'
    assert isinstance(fixture_name, str), f'{repr(fixture_name)} not string.'

    # Attempt to..
    try:
        # Function wrapping this fixture generator with type-checking dynamically
        # generated by @beartype.
        fixture_func_checked = beartype(fixture_func)

        @wraps(fixture_func)
        def _beartype_fixture_wrapper(*args, **kwargs):
            f'''
            :func:`beartype.beartype`-decorated fixture generator wrapping the
            original "{fixture_func.__qualname__}" fixture with type-checking.
            '''

            # Attempt to defer to this type-checked fixture function wrapper.
            #
            # Note that pytest fixtures defined as generators are prohibited
            # from returning values. Ergo, the more constrained (and slightly
            # more efficient) "yield from" rather than full-blown (and slightly
            # less efficient) "return (yield from ...)" expression suffices.
            try:
                yield from fixture_func_checked(*args, **kwargs)
            # If doing so raises a @beartype-specific call-time exception (e.g.,
            # due to type-checking violation), squelch this exception and yield
            # a placeholder object encapsulating this exception instead.
            except BeartypeException as exception:
                yield BeartypeFixtureFailure(fixture_name, exception)
    # If doing so raises *ANY* decoration-time exception (e.g., due to a
    # PEP-noncompliant type hint), squelch this exception and replace the
    # original fixture with a wrapper unconditionally yielding a placeholder
    # object encapsulating this exception whenever called.
    except Exception as exception:
        @wraps(fixture_func)
        def _beartype_fixture_wrapper(
            *args, __beartype_exception__=exception, **kwargs):
            f'''
            Wrapper unconditionally yielding a placeholder object encapsulating
            a decoration-time exception raised by the :func:`beartype.beartype`
            decorator on decorating the original "{fixture_func.__qualname__}"
            fixture with type-checking.

            See Also
            --------
            :func:`._beartype_fixture_sync_generator`
                Further details.
            '''

            # Yield a placeholder object encapsulating this exception.
            yield BeartypeFixtureFailure(fixture_name, __beartype_exception__)

    # Return this @beartype-decorated fixture wrapper.
    return _beartype_fixture_wrapper

# ....................{ DECORATORS ~ async                  }....................
@beartype
def beartype_fixture_async_nongenerator(
    fixture_func: Callable, fixture_name: str) -> Callable:
    '''
    Custom :mod:`beartype` decorator unique to :mod:`pytest` asynchronous
    non-generator fixtures (i.e., fixture coroutines), dynamically generating
    and returning a new :func:`beartype.beartype`-decorated asynchronous
    non-generator fixture function wrapping the passed asynchronous
    non-generator fixture function with type-checking.

    Note that this decorator intentionally does *not* handle asynchronous
    generator fixtures, which the sibling
    :func:`.beartype_fixture_async_generator` decorator handles instead. Why?
    Because asynchronous generators (unlike coroutines) *cannot* be awaited;
    they can only be asynchronously iterated. Moreover, the kind of the wrapper
    itself matters: pytest plugins supporting asynchronous fixtures (e.g.,
    "pytest-asyncio") introspect the kind of each fixture function to decide
    how to run that fixture. Wrapping an asynchronous generator fixture with a
    coroutine wrapper would thus misrepresent that fixture to those plugins.

    Parameters
    ----------
    fixture_func : Callable
        Low-level pure-Python function implementing this high-level fixture.
    fixture_name : str
        Fully-qualified name of this fixture.
    '''
    assert callable(fixture_func), f'{repr(fixture_func)} uncallable.'
    assert isinstance(fixture_name, str), f'{repr(fixture_name)} not string.'

    # Attempt to..
    try:
        # Function wrapping this fixture function with type-checking dynamically
        # generated by @beartype.
        fixture_func_checked = beartype(fixture_func)

        @wraps(fixture_func)
        async def _beartype_fixture_wrapper(*args, **kwargs):
            f'''
            :func:`beartype.beartype`-decorated fixture function wrapping the
            original "{fixture_func.__qualname__}" fixture with type-checking.
            '''

            # Attempt to defer to this type-checked fixture function wrapper.
            try:
                return await fixture_func_checked(*args, **kwargs)
            # If doing so raises a @beartype-specific call-time exception (e.g.,
            # due to type-checking violation), squelch this exception and return
            # a placeholder object encapsulating this exception instead.
            except BeartypeException as exception:
                return BeartypeFixtureFailure(fixture_name, exception)
    # If doing so raises *ANY* decoration-time exception (e.g., due to a
    # PEP-noncompliant type hint), squelch this exception and replace the
    # original fixture with a wrapper unconditionally returning a placeholder
    # object encapsulating this exception whenever called.
    except Exception as exception:
        # Defer asyncio-specific imports as late as feasible.
        from asyncio import sleep as asyncio_sleep

        @wraps(fixture_func)
        async def _beartype_fixture_wrapper(
            *args, __beartype_exception__=exception, **kwargs):
            f'''
            Wrapper unconditionally returning a placeholder object encapsulating
            a decoration-time exception raised by the :func:`beartype.beartype`
            decorator on decorating the original "{fixture_func.__qualname__}"
            fixture with type-checking.

            Note that this exception is intentionally passed as a hidden
            optional ``__beartype_exception__`` parameter to this fixture
            wrapper. Why? Because if we do *not* do that, then CPython complains
            that the ``__beartype_exception__`` attribute is inaccessible to the
            body of this closure. Why? No idea. Closure mechanics frighten me,
            honestly:

                NameError: cannot access free variable '__beartype_exception__'
                where it is not associated with a value in enclosing scope
            '''

            # Silently reduce to an asynchronous noop. *ALL* coroutines are
            # required to call the "await" keyword at least once. Since the
            # placeholder object returned below is synchronous and thus *CANNOT*
            # be asynchronously awaited, this fallback wrapper has *NO* recourse
            # but to asynchronously await a minimal-cost awaitable. Aaaaaaand...
            #
            # This is why the "asyncio" API is Python's most hated. We sigh!
            await asyncio_sleep(0)

            # Return a placeholder object encapsulating this exception.
            return BeartypeFixtureFailure(fixture_name, __beartype_exception__)

    # Return this @beartype-decorated fixture wrapper.
    return _beartype_fixture_wrapper


@beartype
def beartype_fixture_async_generator(
    fixture_func: Callable, fixture_name: str) -> Callable:
    '''
    Custom :mod:`beartype` decorator unique to :mod:`pytest` asynchronous
    generator fixtures, dynamically generating and returning a new
    :func:`beartype.beartype`-decorated asynchronous generator fixture function
    wrapping the passed asynchronous generator fixture function with
    type-checking.

    Parameters
    ----------
    fixture_func : Callable
        Low-level pure-Python asynchronous generator implementing this
        high-level fixture.
    fixture_name : str
        Fully-qualified name of this fixture.
    '''
    assert callable(fixture_func), f'{repr(fixture_func)} uncallable.'
    assert isinstance(fixture_name, str), f'{repr(fixture_name)} not string.'

    # Attempt to..
    try:
        # Function wrapping this fixture generator with type-checking
        # dynamically generated by @beartype.
        fixture_func_checked = beartype(fixture_func)

        @wraps(fixture_func)
        async def _beartype_fixture_wrapper(*args, **kwargs):
            f'''
            :func:`beartype.beartype`-decorated fixture generator wrapping the
            original "{fixture_func.__qualname__}" fixture with type-checking.
            '''

            # Attempt to defer to this type-checked fixture function wrapper.
            #
            # Note that asynchronous generators (unlike synchronous generators)
            # prohibit the "yield from" expression. CPython raises a fatal
            # "SyntaxError" at importation time for *ANY* submodule attempting
            # to call "yield from" from an asynchronous generator. Ergo, the
            # semantically equivalent (but syntactically permissible) "async
            # for" statement is deferred to instead.
            try:
                async for fixture_value in fixture_func_checked(
                    *args, **kwargs):
                    yield fixture_value
            # If doing so raises a @beartype-specific call-time exception (e.g.,
            # due to type-checking violation), squelch this exception and yield
            # a placeholder object encapsulating this exception instead.
            except BeartypeException as exception:
                yield BeartypeFixtureFailure(fixture_name, exception)
    # If doing so raises *ANY* decoration-time exception (e.g., due to a
    # PEP-noncompliant type hint), squelch this exception and replace the
    # original fixture with a wrapper unconditionally yielding a placeholder
    # object encapsulating this exception whenever called.
    except Exception as exception:
        @wraps(fixture_func)
        async def _beartype_fixture_wrapper(
            *args, __beartype_exception__=exception, **kwargs):
            f'''
            Wrapper unconditionally yielding a placeholder object encapsulating
            a decoration-time exception raised by the :func:`beartype.beartype`
            decorator on decorating the original "{fixture_func.__qualname__}"
            fixture with type-checking.

            See Also
            --------
            :func:`.beartype_fixture_async_nongenerator`
                Further details.
            '''

            # Yield a placeholder object encapsulating this exception.
            yield BeartypeFixtureFailure(fixture_name, __beartype_exception__)

    # Return this @beartype-decorated fixture wrapper.
    return _beartype_fixture_wrapper
