#!/usr/bin/env python3
# --------------------( LICENSE                            )--------------------
# Copyright (c) 2024-2026 Beartype authors.
# See "LICENSE" for further details.

'''
Plugin **pytest test type-checking integration tests** (i.e., tests
validating the ``--beartype-tests`` command-line option accepted by this
plugin).
'''

# ....................{ TESTS                              }....................
def test_option_beartype_tests(tmp_path: 'pathlib.Path') -> None:
    '''
    Integration test validating that the ``--beartype-tests`` option accepted by
    this plugin correctly type-checks *all* :mod:`pytest` test functions.

    Parameters
    ----------
    tmp_path: pathlib.Path
        Temporary directory uniquely isolated to this test.
    '''

    # Defer test-specific imports.
    from pytest_beartype_test._util.path.pytpathtest import (
        get_test_func_data_option_beartype_tests)
    from pytest_beartype_test._util.pytcmdrun import run_pytest_plugin_test

    # "subprocess.CompletedProcess" object encapsulating the result of running
    # a shell command forking the active Python interpreter as a subprocess
    # executing the "pytest" package installed under that interpreter passed
    # this plugin-specific option, which then collects and executes this test
    # submodule subject to this option.
    command_result = run_pytest_plugin_test(
        test_submodule_file=(
            get_test_func_data_option_beartype_tests()),
        tmp_path=tmp_path,
        pytest_options=(
            # Instruct the third-party "pytest-asyncio" plugin to implicitly
            # collect and execute *ALL* asynchronous tests in this test
            # submodule. By default, that plugin only collects and executes
            # asynchronous tests explicitly decorated by the
            # "@pytest.mark.asyncio" marker.
            '--override-ini', 'asyncio_mode=auto',

            # Instruct this plugin to type-check *ALL* tests defined by the
            # passed Python file.
            '--beartype-tests',
        ),
    )

    # Assert this command succeeded by returning zero exit status.
    #
    # Note this assertion *MUST* be directly performed by this test rather
    # than the run_pytest_plugin_test() utility function called above.
    # Why? Pytest rewrites assertions via abstract syntax tree (AST)
    # transformations applied by non-trivial import hooks, which *ONLY*
    # apply to collected tests. (Non-trivial. It is what it is.)
    assert command_result.returncode == 0, (
        f'Integration test "test_option_beartype_tests" '
        f'"pytest" subprocess exit status {command_result.returncode} != 0:'
        f'\n\n[standard output]\n{command_result.stdout}'
        f'\n\n[standard error]\n{command_result.stderr}'
    )


def test_option_beartype_tests_parametrized_cache(
    pytester: 'pytest.Pytester') -> None:
    '''
    Integration test validating that the ``--beartype-tests`` option accepted by
    this plugin correctly type-checks a parametrized :mod:`pytest` test function
    in a safe manner efficiently reusing the wrapper type-checking that function
    dynamically generated by the first parametrization of that function.

    This test is strongly inspired by a similar test authored by @adamtheturtle
    (Adam Dangoor) for the test suite of the downstream `pytest-beartype-tests`_
    plugin. Thanks so much, @adamtheturtle. You are a beacon of light to QA.

    .. _pytest-beartype-tests:
       https://github.com/adamtheturtle/pytest-beartype-tests/blob/main/tests/test_plugin.py
    '''

    pytester.makeconftest(source=_CONFTEST_BEARTYPE_CALL_COUNT)
    pytester.makepyfile(_TEST_OPTION_BEARTYPE_TESTS_PARAMETRIZED_CACHE)

    # Fork a "pytest" subprocess running the tests defined by this test file
    # against this "conftest.py" plugin.
    result = pytester.runpytest(
        '--beartype-tests',

        #FIXME: *SUPER-LAME*. QA Jesus wept.
        # Disable the third-party "pytest-asyncio" plugin. Failing to do so
        # causes that plugin to issue a non-fatal warning, which then causes
        # this test suite to promote that warning into a fatal exception and
        # thus test failure. Seriously. What were they thinking?
        '-p', 'no:asyncio',
    )

    result.assert_outcomes(passed=4)

# ....................{ PRIVATE ~ globals                  }....................
#FIXME: *AWKARD*. Shift into a new submodule residing in the
#"pytest_beartype_test.a90_func.data" subpackage, please. *sigh*
_CONFTEST_BEARTYPE_CALL_COUNT = '''
# ....................{ BEARTYPE                           }....................
import beartype

# Original @beartype decorator *BEFORE* being monkey-patched below. *sigh*
from beartype import beartype as _beartype_real


def _beartype_fake(*args, **kwargs):
    """
    Fake :func:`beartype.beartype` decorator monkey-patched to count the total
    number of times that the :mod:`beartype` decorator has been invoked across
    the active Python subprocess.
    """

    # Enable this global to be incremented below.
    global _beartype_call_count

    # Increment this total.
    _beartype_call_count += 1

    # Defer to the original @beartype decorator.
    return _beartype_real(*args, **kwargs)


# Monkey-patch the @beartype decorator to count the number of times that
# decorator has been invoked. This may be awful, but awful at least works.
beartype.beartype = _beartype_fake


_beartype_call_count = 0
"""
Total number of times that a test requiring the :func:`.beartype_call_count`
fixture defined above has implicitly invoked the :mod:`beartype` decorator.
"""

# ....................{ PYTEST                             }....................
import pytest


@pytest.fixture
def beartype_call_count() -> int:
    """
    Test-scoped fixture whose value is the total number of times the
    :mod:`beartype` decorator has been invoked across the active Python
    subprocess.

    Tests typically require this fixture to assert that this plugin has
    efficiently reused previously memoized type-checking wrapper test functions
    rather than inefficiently regenerating those functions.
    """

    # Return this number as the value of this fixture presented to tests
    # requiring this fixture. Welcome to pytest, yo.
    return _beartype_call_count
'''


#FIXME: *AWKARD*. Shift into a new submodule residing in the
#"pytest_beartype_test.a90_func.data" subpackage, please. *sigh*
_TEST_OPTION_BEARTYPE_TESTS_PARAMETRIZED_CACHE = '''
import pytest

@pytest.mark.parametrize('parameter', [
    'Made for our searching: yes, in spite of all,',
    'Some shape of beauty moves away the pall',
    'From our dark spirits. Such the sun, the moon,',
    'Trees old and young, sprouting a shady boon',
])
def test_option_beartype_tests_parametrized_cache_driver(
    parameter: str, beartype_call_count: int) -> None:
    """
    Unit test validating that the ``--beartype-tests`` option accepted by
    this plugin correctly type-checks a parametrized :mod:`pytest` test function
    in a safe manner efficiently reusing the wrapper type-checking that function
    dynamically generated by the first parametrization of that function.
    """

    # Assert that only the first of these parametrizations invokes the
    # @beartype decorator, thus asserting that each of these
    # parametrizations efficiently reuses the wrapper type-checking this
    # parametrized test dynamically generated by the first
    # parametrization of this test (rather than inefficiently generating
    # that wrapper on each parametrization). This just how we roll.
    assert beartype_call_count == 1
'''
