#!/usr/bin/env python3
# --------------------( LICENSE                            )--------------------
# Copyright (c) 2024-2026 Beartype authors.
# See "LICENSE" for further details.

'''
Plugin-specific **test type-checking** (i.e., :mod:`pytest` hook functions
generalizing the runtime behaviour of :mod:`pytest` to type-check collected
user-defined :mod:`pytest` tests with :mod:`beartype`).
'''

# ....................{ IMPORTS                            }....................
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# CAUTION: Avoid importing from *ANY* packages at global scope to improve pytest
# startup performance. The sole exception is the "pytest" package itself. Since
# pytest has presumably already imported and run this plugin, the "pytest"
# package has presumably already been imported. Ergo, importing from that
# package yet again incurs no further costs.
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
import pytest

# ....................{ HOOKS ~ tests                      }....................
def pytest_collection_modifyitems(
    config: 'pytest.Config', items: list['pytest.Item']) -> None:
    '''
    Conditionally decorate *all* collected test functions by the
    :func:`beartype.beartype` decorator if instructed to do so by the user
    (e.g., if passed the ``--beartype-tests`` command-line option).
    '''

    # ....................{ IMPORTS ~ early                }....................
    # Defer hook-specific imports required to noop below.
    from pytest_beartype._util.pytest.utilpytoption import is_pytest_option_bool

    # ....................{ NOOP                           }....................
    # If *NOT* instructed by the user to type-check tests, reduce to a noop.
    if not is_pytest_option_bool(config, 'beartype_tests'):
        return
    # Else, the user instructed this plugin to type-check tests.

    # ....................{ IMPORTS ~ late                 }....................
    # Defer hook-specific imports as late as feasible to minimize startup
    # costs associated with merely enabling this plugin.
    from beartype import beartype
    from collections.abc import Callable
    from pytest import Function
    from types import ModuleType

    # ....................{ LOCALS                         }....................
    # Dictionary mapping from each 3-tuple "(test_module, test_type, test_name)"
    # describing each user-defined test function collected by pytest to the
    # wrapper dynamically generated by @beartype type-checking that function.
    # This dictionary acts as a crude (albeit effective) cache optimizing the
    # edge case of parametrized tests. For each parametrized test, pytest
    # collects multiple testable items iterated below all sharing the same
    # underlying test function and thus type-checking wrapper. This dictionary
    # enables these wrappers to be trivially shared across the multiple testable
    # items encapsulating each parametrized test. Although the type-checking
    # wrappers generated by @beartype are fast, the @beartype decorator itself
    # is comparatively slow. This dictionary has been profiled to reduce the
    # cost of collecting parametrized tests when this plugin is enabled.
    test_func_data_to_wrapper: (
        dict[tuple[ModuleType | None, type | None, str], Callable[..., object]]
    ) = {}

    # ....................{ TYPE-CHECK                     }....................
    # For each user-defined testable item collected by pytest...
    for item in items:
        # If this item is *NOT* a conventional test function, this item is an
        # unconventional test object currently unsupported by this plugin (e.g.,
        # Sybil-generated "doctest" item).
        if not isinstance(item, Function):
            continue
        # Else, this item is a conventional test function.

        # 3-tuple "(test_module, test_type, test_name)" describing this test
        # function, suitable for use as the dictionary key caching the
        # type-checking wrapper generated below. This tuple is guaranteed to be
        # both hashable *AND* unique across all collected test functions.
        #
        # Note that this pytest item itself is *NOT* guaranteed to be hashable
        # and is thus unsuitable for use as this key. Notably, pytest items
        # encapsulating parametrized tests parametrized by unhashable objects
        # are themselves unhashable.
        test_func_data = (item.module, item.cls, item.originalname)

        # Type-checking wrapper previously generated by the @beartype decorator
        # during a prior iteration of this "for" loop if any *OR* "None"
        # otherwise (i.e., if this is the first iteration visiting this
        # function, as is the common case for all tests *EXCEPT* parametrized).
        test_func_wrapper = test_func_data_to_wrapper.get(test_func_data)

        # If this is the first iteration visiting this function...
        if test_func_wrapper is None:
            # Wrapper type-checking this test function, cached back into this
            # dictionary for lookup by a subsequent iteration of this loop.
            test_func_wrapper = test_func_data_to_wrapper[test_func_data] = (
                beartype(item.obj))
        # Else, this is a subsequent iteration visiting this function.
        #
        # In either case, this type-checking wrapper is now guaranteed to exist.

        # Replace this non-type-checked test function with this previously
        # generated type-checking wrapper function.
        item.obj = test_func_wrapper
